### ISSUE TITLE
Compilation errors with 999-SNAPSHOT

### ISSUE THREAD

**Issue by jsmrcka** [quarkus-qe/quarkus-openshift-test-suite#442]
When running `quarkus-core-only` profile, e.g. in `JVM build - Quarkus main` GH action, following compilation errors occur:
- `/home/runner/work/quarkus-openshift-test-suite/quarkus-openshift-test-suite/common/src/main/java/io/quarkus/ts/openshift/common/util/OpenShiftUtil.java:[23,15] package okhttp3 does not exist`.
  - The unused import can be removed.
- `/home/runner/work/quarkus-openshift-test-suite/quarkus-openshift-test-suite/common/src/main/java/io/quarkus/ts/openshift/common/util/ReadinessUtil.java:[11,55] package io.fabric8.kubernetes.client.internal.readiness does not exist`.
  - Caused by https://github.com/quarkusio/quarkus/pull/26107.
